# Generated by Django 4.2.16 on 2024-10-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='image/q_img', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
