# Generated by Django 4.2.16 on 2024-11-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
