# Generated by Django 4.2.16 on 2024-10-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-addres')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Publication')),
            ],
        ),
    ]
