# Generated by Django 4.2.16 on 2024-10-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'лайки', 'verbose_name_plural': 'лайк'},
        ),
    ]
