# Generated by Django 4.2.16 on 2024-11-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_question_managers_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
