# Generated by Django 4.2.16 on 2024-11-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_question_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='ip',
        ),
    ]
