# Generated by Django 4.2.16 on 2024-11-10 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_question_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'лайки ответов',
                'verbose_name_plural': 'лайк ответа',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'лайки вопросов',
                'verbose_name_plural': 'лайк вопроса',
                'unique_together': {('user', 'pos')},
            },
        ),
        migrations.RemoveField(
            model_name='likes',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dislikes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
