# Generated by Django 4.2.16 on 2024-11-10 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_commentlike_questionlike_remove_likes_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlike',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionlikes', to='app.question', verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
