# Generated by Django 4.2.16 on 2024-11-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_questionlike_pos_alter_questionlike_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-addres')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'дизлайки',
                'verbose_name_plural': 'дизлайк',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-addres')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'лайки',
                'verbose_name_plural': 'лайк',
            },
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='QuestionLike',
        ),
    ]
